version: "3"
services: 
  web:
    build: 
      context: ./docker/nginx
    container_name: "laravel-study_nginx"
    depends_on: 
      - php
    links:
      - php:phpfpm
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports: 
      - "8080:80"
  php:
    build: 
      context: ./docker/php
    container_name: "laravel-study_php"
    environment: 
      DB_HOST: mysql
    volumes: 
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./:/var/www
  mysql:
    build: 
      context: ./docker/mysql
    container_name: "laravel-study_mysql"
    environment: 
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - TZ=Asia/Tokyo
    volumes: 
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports: 
      - 3306:${DB_PORT}