version: "3"
services: 
  web:
    build: 
      context: ./docker/nginx
    container_name: "laravel-study_nginx"
    depends_on: 
      - php
    ports: 
      - "8080:80"
  php:
    build: 
      context: ./docker/php
    container_name: "laravel-study_php"
    environment: 
      DB_HOST: mysql
    volumes: 
      - ./:/src
  mysql:
    build: 
      context: ./docker/mysql
    container_name: "laravel-study_mysql"
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sample
      - MYSQL_USER=sample
      - MYSQL_PASSWORD=sample
      - TZ=Asia/Tokyo
    volumes: 
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports: 
      - 3306:3306